//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomAdminEditonBeta
{
    using DiplomAdminEditonBeta.Views.PagesTask;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Point
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public string Name { get; set; }
        public int ProductCount { get; set; }
        public int IdTask { get; set; }
        public int Position { get; set; }
        public string Address { get; set; }
        public virtual Client Client { get; set; }
        public virtual Task Task { get; set; }

        public List<Client> clientsList
        {
            get
            {
                if (VendorsAndConsumptionsPage.ChosedClient == null)
                    return null;
                return (List<Client>)VendorsAndConsumptionsPage.ChosedClient.Where(p => p.TypeId == Client.TypeId).ToList();
            }
        }
    }
}
