//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomAdminEditonBeta
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Point = new HashSet<Point>();
            this.TransportationCost = new HashSet<TransportationCost>();
            this.Service = new HashSet<Service>();
            this.Constraint = new HashSet<Constraint>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Conclusion { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> CountRow { get; set; }
        public Nullable<int> CountColumn { get; set; }
        public virtual Carrier Carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Point { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationCost> TransportationCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constraint> Constraint { get; set; }

        public string Clients
        {
            get
            {
                List<string> vs = Point.Select(p => p.Client).Select(p => p.CompanyName).Distinct().ToList();
                string s = "";
                bool first = true;
                foreach (string r in vs)
                {
                    if (first)
                    {
                        first = false;
                        s = r;
                        continue;
                    }
                    s += "\n" + r;
                }
                return s;
            }
        }

        public string CarrierName
        {
            get
            {
                if (Carrier == null)
                    return "";
                return Carrier.Name;
            }
        }
    }
}
